- src/components/Players/CardPicker/CardPicker.css
- src/components/Players/CardPicker/CardPicker.test.tsx
- src/components/Players/CardPicker/CardPicker.tsx
- src/components/Players/PlayerCard/PlayerCard.tsx
- src/service/games.ts
> feat: add coffee card

- README.md
- src/components/Players/PlayerCard/PlayerCard.test.tsx
- src/components/Players/Players.test.tsx
- src/components/Poker/CreateGame/CreateGame.test.tsx
- src/components/Poker/CreateGame/CreateGame.tsx
Improve unit test coverage by adding missing unit tests
> Improve unit test coverage

- public/index.html
Update site title and description
> doc: update site title and description

- src/App.tsx
- src/components/Footer/Footer.css
- src/components/Players/CardPicker/CardPicker.css
- src/components/Players/CardPicker/CardPicker.tsx
- src/components/Players/PlayerCard/PlayerCard.css
- src/components/Players/PlayerCard/PlayerCard.tsx
- src/components/Players/Players.css
- src/components/Poker/CreateGame/CreateGame.css
- src/components/Poker/GameArea/GameArea.css
- src/components/Poker/GameController/GameController.css
- src/components/Poker/GameController/GameController.tsx
- src/components/Poker/JoinGame/JoinGame.css
- src/components/Poker/Poker.test.tsx
- src/components/Poker/RecentGames/RecentGames.css
- src/components/Toolbar/Toolbar.css
- src/components/Toolbar/Toolbar.test.tsx
- src/components/Toolbar/Toolbar.tsx
- src/index.tsx
- src/pages/HomePage/HomePage.tsx
- src/styles/styles.css
Fix below minor ui issues
1. Coffee card alignment
2. Home page image and menu issues.
Refactor: Extract colors as css variables
> Fix alignment

- src/components/Players/CardPicker/CardConfigs.ts
- src/components/Players/CardPicker/CardPicker.test.tsx
- src/components/Players/CardPicker/CardPicker.tsx
- src/components/Players/PlayerCard/PlayerCard.tsx
- src/components/Poker/CreateGame/CreateGame.css
- src/components/Poker/CreateGame/CreateGame.test.tsx
- src/components/Poker/CreateGame/CreateGame.tsx
- src/components/Poker/GameController/GameController.test.tsx
- src/components/Poker/GameController/GameController.tsx
- src/pages/HomePage/HomePage.css
- src/pages/HomePage/HomePage.tsx
- src/repository/firebase.ts
- src/service/games.ts
- src/types/game.ts
Add new feature of Tshirt sizing and short fibonacci sizing.
Also, make the pass card values with random emoji, not just coffee anymore,
https://github.com/hellomuthu23/planning-poker/projects/1#card-61673291
> feat: Add short fibonacci and tshirt sizing

- public/index.html
just a tiny fix to the page title
> fix a typo in the page title

- src/App.tsx
- src/components/Players/PlayerCard/PlayerCard.css
- src/components/Players/PlayerCard/PlayerCard.test.tsx
- src/components/Players/PlayerCard/PlayerCard.tsx
- src/components/Players/Players.test.tsx
- src/components/Players/Players.tsx
- src/components/Poker/GameArea/GameArea.tsx
- src/components/Poker/JoinGame/JoinGame.test.tsx
- src/components/Poker/JoinGame/JoinGame.tsx
- src/components/Poker/Poker.test.tsx
- src/components/Poker/Poker.tsx
- src/pages/JoinPage/JoinPage.tsx
- src/repository/firebase.ts
- src/repository/localStorage.ts
- src/service/players.ts
Added a delete player feature for the moderator to remove players from the game.
> feat: add delete player

- .github/workflows/deploy-to-firebase-on-master.yml
- .github/workflows/deploy-to-firebase-on-pr.yml
- .gitignore
- src/repository/firebase.ts
Extract firebase conf values as environment variables
> chore: extract firebase vars

- .github/workflows/deploy-to-firebase-on-pr.yml
> chore: fix pr deployment

- package.json
- src/components/Poker/CreateGame/CreateGame.test.tsx
- src/components/Poker/CreateGame/CreateGame.tsx
- yarn.lock
There's a neat lil package that has a bunch of random words. So, whenever a user goes to the game page they get a random session name (colour + animal) and user name (Star Wars character) using the [unique names generator](https://www.npmjs.com/package/unique-names-generator) package. Also updated the unit tests to reflect the change.
> Random names

- src/service/games.test.ts
- src/service/players.test.ts
- src/service/players.ts
I was bored, and already writing tests, so I thought why not. So here's a bunch of unit tests for the two services that had stuff to test.
> Unit tests for two services

- src/components/Players/PlayerCard/PlayerCard.tsx
just a simple fix so you can see the entire player's name
> fix: add attr title to player name

- src/components/Poker/CreateGame/CreateGame.tsx
- src/components/Poker/JoinGame/JoinGame.tsx
Prevents joining and creating a duplicate session
> fix: prevent duplicate join or session

- src/components/Players/PlayerCard/PlayerCard.css
> fix: fix delete icon space issue

- src/components/Players/CardPicker/CardConfigs.ts
add missing short fib number - 1
> fix: add missing short fib number

- src/components/Poker/RecentGames/RecentGames.test.tsx
- src/components/Poker/RecentGames/RecentGames.tsx
- src/repository/localStorage.ts
- src/service/games.test.ts
- src/service/games.ts
- src/service/players.test.ts
- src/service/players.ts
- src/types/player.ts
Remove player games check from firestore to fix db read quota issue
> fix: fix quota issue

- public/index.html
Comply with EU law
https://cookieinfoscript.com/
> feat: add cookie notice

- src/App.tsx
- src/components/Footer/Footer.css
- src/components/Footer/Footer.tsx
- src/pages/HomePage/HomePage.tsx
remove the footer on child pages. Keep it only on the Parent page and add buymeacoffee link in footer
> fix: fix footer

- public/locales/zh-Hant/translation.json
- src/components/LanguageControl/LanguageControl.tsx
> feat: add zh-hant i18n

- src/components/Players/CardPicker/CardConfigs.ts
- src/components/Players/CardPicker/CardPicker.test.tsx
- src/components/Players/CardPicker/CardPicker.tsx
- src/components/Players/PlayerCard/PlayerCard.test.tsx
- src/components/Players/PlayerCard/PlayerCard.tsx
- src/components/Players/Players.test.tsx
- src/components/Poker/CreateGame/CreateGame.css
- src/components/Poker/CreateGame/CreateGame.test.tsx
- src/components/Poker/CreateGame/CreateGame.tsx
- src/components/Poker/GameArea/GameArea.test.tsx
- src/components/Poker/GameController/GameController.test.tsx
- src/components/Poker/GameController/GameController.tsx
- src/components/Poker/Poker.test.tsx
- src/service/games.test.ts
- src/service/players.test.ts
- src/types/game.ts
Add new custom card option where user can enter max of 10 Custom values of any characters
fixes #87
> feat: Add Custom card options feature

- src/components/Players/CardPicker/CardConfigs.ts
- src/components/Poker/CreateGame/CreateGame.test.tsx
Remove default cards from custom cards and let users create their own cards
fixes #98
> Remove default cards from custom cards

- src/components/Players/CardPicker/CardConfigs.ts
fixes https://github.com/hellomuthu23/planning-poker/issues/106
> fix: fix custom card color

- src/components/Poker/Poker.test.tsx
- src/components/Poker/Poker.tsx
fixes #113 - show confirmation when user click back button
> fix: show confirmation when user clicks back button

- src/components/Poker/GameController/GameController.css
- src/components/Poker/GameController/GameController.tsx
- src/service/games.test.ts
- src/service/games.ts
show average decimal in tooltip
> feat: show average decimal in tooltip

- src/components/Poker/GameController/GameController.test.tsx
- src/components/Poker/GameController/GameController.tsx
- src/service/games.test.ts
- src/service/games.ts
- src/types/game.ts
Allow users to enter story name or number
> feat: add option to enter story name

- src/repository/firebase.ts
Enable firebase api long polling to fix proxy issues on some corporate network
> Enable auto detect long polling

- package.json
- public/locales/de-DE/translation.json
- public/locales/fr/translation.json
- src/App.test.tsx
- src/App.tsx
- src/components/LanguageControl/LanguageControl.test.tsx
- src/components/LanguageControl/LanguageControl.tsx
- src/components/Players/CardPicker/CardPicker.tsx
- src/index.css
- src/pages/AboutPage/AboutPage.tsx
- src/pages/ExamplesPage/ExamplesPage.tsx
- src/pages/GuidePage/GuidePage.tsx
- src/pages/HomePage/HomePage.tsx
- src/pages/JoinPage/JoinPage.tsx
- yarn.lock
Add german and french language
Fix transitions
> fix: fix i18n and transitions

- public/locales/nl-NL/translation.json
- src/components/LanguageControl/LanguageControl.test.tsx
- src/components/LanguageControl/LanguageControl.tsx
- src/components/Players/PlayerCard/PlayerCard.tsx
- src/components/Poker/GameController/GameController.tsx
- src/components/Poker/RecentGames/RecentGames.tsx
- src/components/SVGs/Exit.tsx
- src/components/SVGs/Eye.tsx
- src/components/SVGs/Link.tsx
- src/components/SVGs/Refresh.tsx
- src/components/SVGs/Trash.tsx
Added Dutch Language
Extracted SVGs
> refactor: extract svgs, add dutch language

- src/components/Poker/GameController/GameController.test.tsx
- src/components/Poker/GameController/GameController.tsx
> fix: show average as decimal

- .gitignore
- public/locales/de-DE/translation.json
- public/locales/en/translation.json
- public/locales/fr/translation.json
- public/locales/hi-IN/translation.json
- public/locales/nl-NL/translation.json
- public/locales/ru-RU/translation.json
- public/locales/ta-IN/translation.json
- public/locales/zh-Hant/translation.json
- src/components/Footer/Footer.test.tsx
- src/components/Poker/GameArea/GameArea.tsx
- src/components/Poker/GameController/GameController.test.tsx
- src/components/Poker/GameController/GameController.tsx
- src/service/games.ts
- src/types/game.ts
Auto reveal user votes when all users have voted
> feat: auto reveal when all users have voted

- src/components/Poker/CreateGame/CreateGame.test.tsx
- src/components/Poker/CreateGame/CreateGame.tsx
- src/components/Poker/JoinGame/JoinGame.test.tsx
- src/components/Poker/JoinGame/JoinGame.tsx
> feat: remember user name
